### ISSUE TITLE
Sticky bar with numbers CSS issue

### ISSUE THREAD

**Issue by plingo** [darklow/social-share-kit#15]
Great script!
I notice that in sticky bar the div class="ssk-num" is not enough large to accomodate 2 or more share numbers; please see screenshot.
Thank you.

![share](https://cloud.githubusercontent.com/assets/7942440/7456443/dca451b6-f284-11e4-86fb-9484e0606035.png)

**Comment by darklow** [comment]
I just tried `ssk-num` for example page and it work perfectly.
![image](https://cloud.githubusercontent.com/assets/445304/7783351/7c4f86d2-0148-11e5-920a-ade1c9f05201.png)
1. What os/browser/version are you using?
2. Check if style of the numbers are not affected by any your global CSS.

**Comment by plingo** [comment]
Hi, I’ve changed SSK style and now I can’t debug it anymore.
The issue was detected with Safari 7.1.6 on Mac OS, maybe it was a CSS conflict.
Thank you for your investigation!

Il giorno 23/mag/2015, alle ore 11:37, Kaspars Sprogis notifications@github.com ha scritto:
