### ISSUE TITLE
Buttons don't work with spans inside.

### ISSUE THREAD

**Issue by noeltock** [darklow/social-share-kit#18]
Assuming I have a button:

``` html
<a href class="ssk ssk-facebook"><span class="icon-facebook"></span>Share on Facebook</a>
```

Clicking on the span won't work, just a heads up. Cheers!

**Comment by darklow** [comment]
You don't need SPAN element to add icon. 
Just use following code:

``` html
<a href="" class="ssk ssk-text ssk-facebook">Share on Facebook</a>
```

**Comment by noeltock** [comment]
Correct, but I need the span for a custom design, cheers!

**Comment by darklow** [comment]
Fixed. Thanks for reporting. You can download latest version from master branch until new release is out.

**Comment by noeltock** [comment]
Thanks for that @darklow ! I'll get the client to upgrade too. Here's the screenshot of it (all working :+1: ) so you can see the use-case. Thanks again!

![screen shot 2015-06-25 at 13 03 00](https://cloud.githubusercontent.com/assets/781166/8353047/aaefe80e-1b3a-11e5-836b-bf15903a6dac.png)

**Comment by darklow** [comment]
Glad you worked it out, but i don't see reason why you needed to use SPAN anyways, you could just override CSS a little for existing markup:

``` html
<a href="" class="ssk ssk-text ssk-twitter ssk-lg">Twitter</a>
```

![image](https://cloud.githubusercontent.com/assets/445304/8353385/ecae10bc-1b45-11e5-831d-56a8e11c6526.png)

**Comment by noeltock** [comment]
That's true regarding the span. We do show/hide parts of the text depending on size/responsiveness.

From a project perspective, we try not to inject more CSS into the mix (from third parties). This way we keep naming conventions consistent and the load lean.
