### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by andriytkachiv** [darklow/social-share-kit#20]
Hi, I am using your script with ssl (CloudFlare) and got error " Mixed Content: The page at 'http://example.com' was loaded over HTTPS, but requested an insecure script 'http://graph.facebook.com/?id=https%3A%2F%example.com&callback=cb_facebook_56936'. This request has been blocked; the content must be served over HTTPS"

How can I force Social Share Kit to use SSL? 

Regards

**Comment by darklow** [comment]
Try following:
1) Temporary use `social-share-kit.js` instead of `social-share-kit.min.js`
2) Change this line
https://github.com/darklow/social-share-kit/blob/master/dist/js/social-share-kit.js#L242

``` js
url = 'http://graph.facebook.com/?id=' + shareUrlEnc;
// to
url = '//graph.facebook.com/?id=' + shareUrlEnc;
```

Let me know if it works, then i will make the changes in repo and release fixed version.

**Comment by darklow** [comment]
You know what, never mind, i just tested i should put `https://` always.
Will fix right now and release new version.

**Comment by andriytkachiv** [comment]
Thank you very much! I appreciate your quick support :)

**Comment by darklow** [comment]
The fix is in the newest version:
https://github.com/darklow/social-share-kit/releases
