### ISSUE TITLE
Not sharing correct data

### ISSUE THREAD

**Issue by Hestabit** [darklow/social-share-kit#23]
I am trying to share my page on twitter, g+, facebook, pinterest and linkedin but its not sharing correct data.

I am using this documentation:
http://socialsharekit.com/#documentation

Passing all options inline and also passing options in init function.

But its not sharing the correct data, please help me soon its very urgent. You can check this live on http://bucksme.com

Thanks

**Comment by darklow** [comment]
Please be more specific, what data exactly it is not sharing correctly?

**Comment by Hestabit** [comment]
Thanks :) for your reply, well now I am able to share the things (by using the open graph tags), but I am still facing one issue.
LinkedIn only share correct image first time, after that it share the first image (it might be cache issue), but I am not getting the solution.

**Comment by darklow** [comment]
Looks like i cannot help you, LinkedIn uses image from your meta tags and it is not in any way related to Social Share Kit. You'll have to search for solution elsewhere: https://www.google.lv/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=linkedin%20share%20image%20meta%20tag
