### ISSUE TITLE
Multiple Groups on Single Page

### ISSUE THREAD

**Issue by smayzes** [darklow/social-share-kit#24]
Curious if we can have multiple groups on a single page with different text/titles. 

I tried this with different selectors:

```
SocialShareKit.init({
    selector: '.first .ssk',
    ...
});
```

and

```
SocialShareKit.init({
    selector: '.second .ssk',
    ...
});
```

The first wouldn't work and the second(last) one would work.

**Comment by darklow** [comment]
I refactored JS code to support multiple instances by different selectors.
Please try manually downloading latest JS from https://github.com/darklow/social-share-kit/tree/master/dist/js and see if it fixes your problem.
