### ISSUE TITLE
buttons do not share upon click.

### ISSUE THREAD

**Issue by nickolasnikolic** [darklow/social-share-kit#28]
Hi there, it looks like I have an issue: the share buttons generate without trouble, but do not share upon click.

http://www.list.plus/app/#/shared/82/212

is the test url.

```
<div class="sharing-list ssk-group ssk-xs ssk-count ssk-grayscale" data-url="http://list.plus/app/#/shared/{{list[0].list_owner}}/{{list[0].id}}" data-text="{{list[0].name}}">
  <a href="" class="ssk ssk-facebook"></a>
  <a href="" class="ssk ssk-twitter"></a>
  <a href="" class="ssk ssk-google-plus"></a>
  <a href="" class="ssk ssk-pinterest"></a>
  <a href="" class="ssk ssk-linkedin"></a>
</div>
```

is the html (in angular)

and

SocialShareKit.init({selector: '.sharing-list'});//sharekit

is the call in the controller. It's worth noting that usually there are multiple instances on page, but this is a test case showing it not working on an single instance page.

**Comment by nickolasnikolic** [comment]
Issue resolved. Looks like init was running too early for angular. Issue was resolved by running init after $scope.$apply();

**Comment by benjaminrbarnes** [comment]
How exactly did you get this working? I am trying to use this in a single page Angular app and cannot get it to work. The buttons do not do anything when they are clicked.

**Comment by nickolasnikolic** [comment]
Check list.plus I don't remember the code exactly, but it is functioning
with the caveat of the link count sometimes not working. Best of luck. -nn

**Comment by darklow** [comment]
@benjaminrbarnes It is an AngularJS issue. Use AngularJS `$timeout` to ensure DOM is ready:

``` js
$timeout(function(){
  SocialShareKit.init({selector: '.sharing-list'});
)};
```

Although it is not suggested pattern to manipulate DOM with jQuery from controllers.

**Comment by Jp3rd** [comment]
Hi, I can't seem to share the text data using the Facebook button. I tried using both SocialShareKit.init() and inline data-text. both didn't work too.

**Comment by darklow** [comment]
@Jp3rd It is limitation by Facebook, it will always load data from the page automatically. You can use https://developers.facebook.com/tools/debug/ tool to see what data will be extracted.
