### ISSUE TITLE
Twitter to shut down JSON endpoint that enables share counts

### ISSUE THREAD

**Issue by pagelab** [darklow/social-share-kit#29]
https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

This will happen November 20, and looks like there's no other usable alternative for this.

Would be nice at least to have a caching system to hold the actual count. Is this possible?

**Comment by darklow** [comment]
Unless they will roll out new twitter widgets to play with, it is really hard to say how hard would it be to take count from there.
Let's keep an eye on this issue.
Thanks for posting.

**Comment by pagelab** [comment]
Here's a drop in solution to do this: http://opensharecount.com/ It's not official, though.

**Comment by darklow** [comment]
@pagelab thanks. I saw this one, but I am not sure it is the right one to integrate yet. It is a relatively new service, we don't know reliable it is yet and what are their future plans. Can they hold large amount of data after time. Will they be free etc. I think we need to wait a bit. See what big sites like TechCrunch and others go with. I doubt they will keep these zeros in share counters.

**Comment by darklow** [comment]
But i could integrate custom callbacks in config, so everyone can change endpoints where the number comes from.

**Comment by pagelab** [comment]
This looks like a very balanced solution to me.

**Comment by andriytkachiv** [comment]
So what regarding this issue? Could you please add these callback, or remove twitter API. It looks like it is shut down permanently
