### ISSUE TITLE
Buffer Support?

### ISSUE THREAD

**Issue by jcornelius** [darklow/social-share-kit#31]
Any plans to add Buffer support? https://buffer.com/developers/api

**Comment by darklow** [comment]
Can you be more specific, what are you thinking and what API features you would like to use?
Social Share Kit are just sharing icons.

**Comment by johnnymitch** [comment]
That'd be awesome! Just the "share to buffer" sharing icon :-)

**Comment by darklow** [comment]
Ok, so not the API, but this one:
https://buffer.com/extras/button
I think this sounds logic and doable :)
