### ISSUE TITLE
Google+ icon is old

### ISSUE THREAD

**Issue by fabien** [darklow/social-share-kit#36]
I believe the new icon should be like this: http://fortawesome.github.io/Font-Awesome/icon/google-plus/

While Google+ is almost dead, oAuth logins through Google itself tend to use this icon. Preferably, a `.ssk-google-plus-new` and `.ssk-google-plus-alt` (without the plus sign) should be added to the font.

**Comment by darklow** [comment]
Replaced to new icon.
If needed old version of g+ icon available using `.ssk-google-plus-old` class

**Comment by fabien** [comment]
@darklow that was fast! Thanks!

**Comment by darklow** [comment]
Just released newest version with new G+ icon! :)
