### ISSUE TITLE
Shopify?

### ISSUE THREAD

**Issue by MiggyS** [darklow/social-share-kit#43]
Any idea why the popups wouldn't be working in a shopify theme? The js seems to load just fine. But no even fires and it just reloads the page instead of making the popup happen.

**Comment by darklow** [comment]
Make sure you have initiated it too:

``` html
<script type="text/javascript">
SocialShareKit.init();
</script>
```

**Comment by MiggyS** [comment]
Had it in the head, worked once I moved it down to `</body>`

Thanks for the quick reply darklow!
