### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by alexandernst** [darklow/social-share-kit#44]
Can you publish this library to NPM too, please?

**Comment by alexandernst** [comment]
I created the needed files and published the library here `https://www.npmjs.com/package/social-share-kit` as I needed the support in NPM ASAP.

I'll transfer the ownership to you, just ping me.

**Comment by darklow** [comment]
Thanks. Here is my NPM user for transferring rights:
https://www.npmjs.com/~darklow

**Comment by alexandernst** [comment]
Great, just transferred the ownership! Thank you for merging
