### ISSUE TITLE
Share url & count is nothing

### ISSUE THREAD

**Issue by Hopelessone** [darklow/social-share-kit#47]
Hi,

I just can across this and want to get rid of "Easy Social Shares" bloatware plugin, however I get nothing when I click share. I'm using wordpress & bootstrap theme, here is the code I'm using:

`<div class="ssk-group ssk-lg ssk-count">
            <a href="" class="ssk ssk-pinterest"></a>
            <a href="" class="ssk ssk-facebook"></a>
            <a href="" class="ssk ssk-twitter"></a>
            <a href="" class="ssk ssk-google-plus"></a>
            <a href="" class="ssk ssk-email"></a>
        </div>`

What do I need to do to get the right share url and count working?

p.s. are you gonna use http://newsharecounts.com for twitter counts now that twitter has taken away the api?
Thanks,

**Comment by darklow** [comment]
1) You have to include SSK .js and .css files
2) Call `SocialShareKit.init()`. If you're using custom selector, make sure it matches your elements. Default is `.ssk`
3) I am not planning to integrate any thirdparty count plugin, but you can use any other count you want.  There is an example on http://socialsharekit.com/, look for `countCallback` parameter.

**Comment by darklow** [comment]
Alright, looks like you resolved your issue helping me you by email.
