### ISSUE TITLE
Facebook share count always 0

### ISSUE THREAD

**Issue by stuartspencer** [darklow/social-share-kit#51]
The share count for Facebook is returning 0 for all requests.

Kaspars Sprogis informed me this is due to a change Facebook have made to their APi recently.

Example URL using socialsharekit (returning 0):
http://socialsharekit.com/

FB Graph query URL:
https://graph.facebook.com/?id=http%3A%2F%2Fsocialsharekit.com%2F

Sample JSON response for the query as of today:

``` javascript
{
   "og_object": {
      "id": "621585654608336",
      "description": "Library of decent and good looking social sharing icons, buttons and popups",
      "title": "Social Share Kit - Social sharing buttons, icons and popups",
      "type": "website",
      "updated_time": "2016-08-15T16:43:50+0000"
   },
   "share": {
      "comment_count": 0,
      "share_count": 189
   },
   "id": "http://socialsharekit.com/"
}
```

**Comment by darklow** [comment]
Included in newest version.
