### ISSUE TITLE
Facebook "F-icon" not centered properly

### ISSUE THREAD

**Issue by BlackSkorpio** [darklow/social-share-kit#54]
As the title says the `f` is not properly centered
No matter what side you put the icons the Facebook `f` is misaligned compared to the others

**Comment by darklow** [comment]
It is not a bug, but a feature. 
It is their official position to be on the right: 
https://commons.wikimedia.org/wiki/File:F_icon.svg

**Comment by BlackSkorpio** [comment]
Hmmm, Ok

But still looks a bit odd when aligned with the rest of the icons :/

**Comment by darklow** [comment]
For me it looks really odd when centered because unconsciously i know how FB logo and icon should be :)

**Comment by BlackSkorpio** [comment]
HAHA Well to be honest with you, I haven't noticed that the F was right aligned officially!

But from "design POV" in this context I still hold my position ;) that it would give a better overall look if it was aligned as the rest of the icons.

**Comment by darklow** [comment]
I just checked biggest share button online services (shareThis, etc) and everybody uses right aligned too, so I guess I'll keep it as it is.
Feel free to override it on your page ;)

``` css
.ssk-facebook:before {
 text-indent: 0;
 margin-right: 0;
}
```

**Comment by BlackSkorpio** [comment]
Yep I will :+1:
