### ISSUE TITLE
Re-initialise SocialShareKit?

### ISSUE THREAD

**Issue by dllabs** [darklow/social-share-kit#55]
I have an Ajax page with "previous" and "next" buttons.  To add the SocialShareKit button to the bottom of each page, I'm calling init() after the ajax query, with the newly retrieved data.
Trouble is, it ends up attaching one SocialShareKit popup for every page that gets scrolled through (that is, every time init() gets called again), so by the time the user clicks the share button, 10 share windows might pop up, one under the other.
Is there a way to destroy/detach/unlink the existing SocialShareKit object whenever the data is replaced? Is there a way to re-initialise the data in JS without calling init() again? Init() is the only method I can find . . .
What's the trick?

thanks

John

**Comment by darklow** [comment]
Fix available in latest version.
Thanks for reporting.

**Comment by crico** [comment]
What is the way to re-initialise it? I can't find it. 

Thanks.

**Comment by darklow** [comment]
Call `init()` one more time (or use your own different selector), it will apply only items that haven't been initialised yet:
https://github.com/darklow/social-share-kit/blob/master/dist/js/social-share-kit.js#L37

**Comment by crico** [comment]
Aha ok, but I need to change the URL over share buttons because I am using an infinite scroll that it loads new articles, is it possible?

**Comment by darklow** [comment]
Yes it is possible, provide different config at `SSK.init(config)`
