### ISSUE TITLE
WhatsApp Share button for mobile

### ISSUE THREAD

**Issue by kelkes** [darklow/social-share-kit#7]
A "Share to Whatsapp" button for mobile devices would be a nice addition to your product.

**Comment by darklow** [comment]
@kelkes I am not sure about mobile buttons. Web based CSS/JS icons don't know anything about your phone, especially does your mobile phone has Whatsapp installed at all. 

Also there is generic Share button in IOS in Safari, where you can see apps where you can share.
I am sure there something similar on Android too.
But i am opened for discussion.

**Comment by kelkes** [comment]
From a pure technical perspective i totally agree but from a more marketing-oriented point of view i want user to share my content more often and WhatsApp is a steadily increasing factor in this game.
Compared to the generic share on iOS or Android using the SocialShareBit buttons is way faster/easier. So i thought that WhatsApp would be a neat addition.

**Comment by darklow** [comment]
Ok, thanks for feedback. I'll think about it. Need to get more info about different devices. 
Currently it looks like all you need is just use `whatsapp://` protocol.
http://www.whatsapp.com/faq/en/android/28000012
However no mentions about IOS there.

But i could definitely start with adding icon and colors and simple `whatsapp://`.
Also related to #5

**Comment by kelkes** [comment]
Great. If you need any help let me know (beside purchasing a license, which i already did _g_)

I've used http://whatsapp-sharing.com/ in another project... maybe this helps

**Comment by gpluess** [comment]
+1 for adding Whatsapp. Unfortunately there is no way to edit the fonts / no description how you've built the fonts, otherwise I could help out with a pull request, too.

**Comment by darklow** [comment]
I just added WhatsApp font icon and colors, however i am not sure if automatic javascript share script is also needed, because of how often whatsapp share will be used.

![image](https://cloud.githubusercontent.com/assets/445304/6635242/274d7928-c96c-11e4-82fa-b11358c21a6b.png)

What do you guys think? 
Would you like me to add automatic javascript which handles calling `whatsapp://send?text=Hello%20World!` on click, or you could just add:

``` html
<a href="whatsapp://send?text=Hello%20World!" class="ssk ssk-whatsapp"></a>
```

by yourself?

**Comment by gpluess** [comment]
Nice! :+1: For me it's fine like that! Thanks!

**Comment by tmblog** [comment]
Excellent thank you. Inline is fine I guess, because there is no need for any popups. I tried this with another script and works fine with ios and android though they were both latest-ish versions so not sure about older versions.

`whatsapp://send?text={title} - {url}`
