### ISSUE TITLE
Setup Scotoma

### ISSUE THREAD

**Issue by in8dna** [darklow/social-share-kit#80]
I've tried the support email... alas

I'd like to finish configuring SSK, but I've got a scotoma (blindspot) on something (not sure).

I've followed the docs, but have no idea what the correct social platform URLs are supposed to be. I want the pages of a blog to be automatically added to the share. I cant get the popup to work, but I think I've got all the files in place and requested. At least the CSS is working.

See; https://syn.wbc.live/a/us-latest-topic-taste-post
you can see the FB link is: https://www.facebook.com/sharer.php?u={url}
But the {url} was just copied from another resource.

I'd like to finish by paying the commercial license (a small perk) is there anyone available?
daniel
daniel@in8dna.com

**Comment by matinfo** [comment]
Hi @in8dna, you need to initial it with:

HTML need to look +/- like this, not need to give URL or other parameter:
```
<div class="ssk-group">
    <a href="" class="ssk ssk-facebook"></a>
    <a href="" class="ssk ssk-twitter"></a>
    <a href="" class="ssk ssk-google-plus"></a>
    <a href="" class="ssk ssk-pinterest"></a>
    <a href="" class="ssk ssk-tumblr"></a>
</div>
```
The URL, title, test of the popup will be first get from, current URL, `<title>` and `<description>` tag of the page.

be also provided from `data-*` attributes or from init options.
```
  SocialShareKit.init({
  selector: '.ssk',
  url: 'https://socialsharekit.com',
  twitter: {
  title: 'Social Share Kit',
  via: 'socialsharekit'
  }
  });
```

For Twitter and Facebook better to use meta-data like mentioned in the doc., example:
```
<meta property="og:site_name" content="Social Share Kit">
<meta property="og:image" content="https://socialsharekit.com/img/avatar.png">
```

Look in the documentation, section *Sharer popup options*

**Comment by in8dna** [comment]
SOLVED: Thank you. 
Leaving the href equal to 'nothing' was _implied_, but not a directive as in 'leave the url empty' because the SSK injects the social company url itself.

My second issue was that the call initialize script needed to be moved lower on the page from the link to the script (script type="text/javascript" src="/ssk/dist/js/social-share-kit.js)

> You must also initialize Social Share Kit plugin. **Put following before your closing </body>** tag or call whenever you want share popups to initialize. 

I simply moved "ipt type="text/javascript">SocialShareKit.init({ forceInit: true });" script down from the link to the files.

Well done support. Thank you

Licensing fee on the way...
