### ISSUE TITLE
Twitter cards

### ISSUE THREAD

**Issue by tmblog** [darklow/social-share-kit#9]
Firstly thanks for the fabulous script.
I have a slight issue.
Even though I have 'twitter card meta tags', for some reason the page title and meta descripton is is being used. Is that the default behaviour? How can I overcome this and use the twitter card tags?

**Comment by darklow** [comment]
It should use `og:*` tags, but i look into this and test it myself.
Thanks for reporting.

**Comment by darklow** [comment]
I resolved this issue and release a new version with the fix.

**Comment by tmblog** [comment]
HI thanks for the prompt reply, will you be able to check what happens when you have og tags and twitter card specific tags. (https://dev.twitter.com/cards/markup), I'm still having some problems.

```
<title>Site title Example.com</title>
<meta name="description" content="A long description from html meta desc.">
<meta property="og:type" content="article">
<meta property="og:url" content="example.com">
<meta property="og:title" content="<title for fb og tags">
<meta property="og:description" content="a long description for fb og tags">
<meta property="og:image" content="http://example.com/images/photo.jpg">
<meta name="twitter:card" content="photo">
<meta name="twitter:site" content="@exampletwit">
<meta name="twitter:desc" content="a long description for twitter card tag"/>
<meta name="twitter:image:src" content="http://example.com/images/photo.jpg">
```

With the above, the html title and and og titles are being fetched first, if I delete the page meta title then og:title - og:description is fetched. If that's deleted then it works with twitter:desc. So only this:

```
<meta name="twitter:card" content="photo">
<meta name="twitter:site" content="@exampletwit">
<meta name="twitter:desc" content="a long description for twitter card tag"/>
<meta name="twitter:image:src" content="http://example.com/images/photo.jpg">
```

WIll you check to see if you also get that?

**Comment by darklow** [comment]
@tmblog There is no such tag `twitter:desc`
I was testing using `twitter:title`,  `twitter:description` and  `twitter:site` - these three meta tags has higher priority than og:\* and `<title>` tags
https://dev.twitter.com/cards/types/summary

`twitter:title` is used as title, `twitter:description` is used as text and `twitter:site` as via parameter.

**Comment by tmblog** [comment]
Ok sorry that was a typo here. It turns out that, if the `twitter:title` is missing then og:\* are used. Perhaps it's worth noting this for other users?

With all twitter card tags present (title, description and site) it works fine.

Anyway thanks for your excellent support, will be buying a license soon.
